### PR TITLE
Remove iframe-phone submodule, replace as node package

### PR DESCRIPTION
**Pull request by sfentress**

### CODE REVIEW

**Comment by scytacki** [comment]
@sfentress looks like you need to update travis.yml to install iframe-phone.

**Comment by sfentress** [comment]
Huh, I thought travis ran `npm install` by default on any project with a package.json file...

**Comment by scytacki** [comment]
probably the `language: ruby` overrides that

**Comment by dougmartin** [comment]
One note, you may want to add `travis_retry` before the npm install like `travis_retry npm install` (https://docs.travis-ci.com/user/common-build-problems/#travis_retry)

**Pull request merged**
